name: zip
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches-ignore:
      - master
  pull_request:
jobs:
  pipeline:
    name: zip
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    timeout-minutes: 40
    env:
      PROJECT_NAME: logstash
      PACKAGE_EXT: zip
    steps:
      - uses: actions/checkout@v1
      - name: Run ZIP
        run: gradle zip
